<?php

class PostModel extends Model
{
    public static $type = 'post';
    /**
     * Return a list of all published posts.
     *
     * @return array
     */
    public static function all($nb = 6)
    {
        $query = new Query([
            'post_type'         => 'post',
            'posts_per_page'    => $nb,
            'post_status'       => 'publish'
        ]);

        return $query->get();
    }

    public static function byCat($categoryId, $except = []){
        return parent::byCategory(self::$type, $categoryId, $except);
    }

    public static function byCommentCnt($except = []){
        return parent::byCommentCount(self::$type,$except );
    }

    public static function aYear($nb = 1)
    {
        return parent::aYearAgo(self::$type, $nb); // TODO: Change the autogenerated stub
    }

    public static function most($nb = 5)
    {
        return parent::mostViewed(self::$type, $nb); // TODO: Change the autogenerated stub
    }

    public static function byTag($tag){
        if(is_array($tag)){

        }
    }

    public static function byDate($date){

    }
} 